const BLOCKS = {
  stone: 'stone',
  granite: 'granite',
  polished_granite: 'polished_granite',
  diorite: 'diorite',
  polished_diorite: 'polished_diorite',
  andesite: 'andesite',
  polished_andesite: 'polished_andesite',
  deepslate: 'deepslate',
  cobbled_deepslate: 'cobbled_deepslate',
  polished_deepslate: 'polished_deepslate',
  calcite: 'calcite',
  tuff: 'tuff',
  dripstone_block: 'dripstone_block',
  grass_block: 'grass_block',
  dirt: 'dirt',
  coarse_dirt: 'coarse_dirt',
  podzol: 'podzol',
  rooted_dirt: 'rooted_dirt',
  mud: 'mud',
  sand: 'sand',
  red_sand: 'red_sand',
  gravel: 'gravel',
  clay: 'clay',
  snow_block: 'snow_block',
  ice: 'ice',
  packed_ice: 'packed_ice',
  blue_ice: 'blue_ice',
  sandstone: 'sandstone',
  chiseled_sandstone: 'chiseled_sandstone',
  cut_sandstone: 'cut_sandstone',
  red_sandstone: 'red_sandstone',
  chiseled_red_sandstone: 'chiseled_red_sandstone',
  cut_red_sandstone: 'cut_red_sandstone',
  oak_log: 'oak_log',
  spruce_log: 'spruce_log',
  birch_log: 'birch_log',
  jungle_log: 'jungle_log',
  acacia_log: 'acacia_log',
  dark_oak_log: 'dark_oak_log',
  mangrove_log: 'mangrove_log',
  cherry_log: 'cherry_log',
  pale_oak_log: 'pale_oak_log',
  stripped_oak_log: 'stripped_oak_log',
  stripped_spruce_log: 'stripped_spruce_log',
  stripped_birch_log: 'stripped_birch_log',
  stripped_jungle_log: 'stripped_jungle_log',
  stripped_acacia_log: 'stripped_acacia_log',
  stripped_dark_oak_log: 'stripped_dark_oak_log',
  stripped_mangrove_log: 'stripped_mangrove_log',
  stripped_cherry_log: 'stripped_cherry_log',
  stripped_pale_oak_log: 'stripped_pale_oak_log',
  oak_wood: 'oak_wood',
  spruce_wood: 'spruce_wood',
  birch_wood: 'birch_wood',
  jungle_wood: 'jungle_wood',
  acacia_wood: 'acacia_wood',
  dark_oak_wood: 'dark_oak_wood',
  mangrove_wood: 'mangrove_wood',
  cherry_wood: 'cherry_wood',
  pale_oak_wood: 'pale_oak_wood',
  stripped_oak_wood: 'stripped_oak_wood',
  stripped_spruce_wood: 'stripped_spruce_wood',
  stripped_birch_wood: 'stripped_birch_wood',
  stripped_jungle_wood: 'stripped_jungle_wood',
  stripped_acacia_wood: 'stripped_acacia_wood',
  stripped_dark_oak_wood: 'stripped_dark_oak_wood',
  stripped_mangrove_wood: 'stripped_mangrove_wood',
  stripped_cherry_wood: 'stripped_cherry_wood',
  stripped_pale_oak_wood: 'stripped_pale_oak_wood',
  oak_planks: 'oak_planks',
  spruce_planks: 'spruce_planks',
  birch_planks: 'birch_planks',
  jungle_planks: 'jungle_planks',
  acacia_planks: 'acacia_planks',
  dark_oak_planks: 'dark_oak_planks',
  mangrove_planks: 'mangrove_planks',
  cherry_planks: 'cherry_planks',
  pale_oak_planks: 'pale_oak_planks',
  oak_leaves: 'oak_leaves',
  spruce_leaves: 'spruce_leaves',
  birch_leaves: 'birch_leaves',
  jungle_leaves: 'jungle_leaves',
  acacia_leaves: 'acacia_leaves',
  dark_oak_leaves: 'dark_oak_leaves',
  mangrove_leaves: 'mangrove_leaves',
  cherry_leaves: 'cherry_leaves',
  azalea_leaves: 'azalea_leaves',
  flowering_azalea_leaves: 'flowering_azalea_leaves',
  vines: 'vines',
  glow_lichen: 'glow_lichen',
  iron_ore: 'iron_ore',
  deepslate_iron_ore: 'deepslate_iron_ore',
  gold_ore: 'gold_ore',
  deepslate_gold_ore: 'deepslate_gold_ore',
  copper_ore: 'copper_ore',
  deepslate_copper_ore: 'deepslate_copper_ore',
  diamond_ore: 'diamond_ore',
  deepslate_diamond_ore: 'deepslate_diamond_ore',
  emerald_ore: 'emerald_ore',
  deepslate_emerald_ore: 'deepslate_emerald_ore',
  coal_ore: 'coal_ore',
  deepslate_coal_ore: 'deepslate_coal_ore',
  redstone_ore: 'redstone_ore',
  deepslate_redstone_ore: 'deepslate_redstone_ore',
  lapis_ore: 'lapis_ore',
  deepslate_lapis_ore: 'deepslate_lapis_ore',
  quartz_ore: 'quartz_ore',
  nether_gold_ore: 'nether_gold_ore',
  ancient_debris: 'ancient_debris',
  obsidian: 'obsidian',
  crying_obsidian: 'crying_obsidian',
  glass: 'glass',
  white_stained_glass: 'white_stained_glass',
  orange_stained_glass: 'orange_stained_glass',
  magenta_stained_glass: 'magenta_stained_glass',
  light_blue_stained_glass: 'light_blue_stained_glass',
  yellow_stained_glass: 'yellow_stained_glass',
  lime_stained_glass: 'lime_stained_glass',
  pink_stained_glass: 'pink_stained_glass',
  gray_stained_glass: 'gray_stained_glass',
  light_gray_stained_glass: 'light_gray_stained_glass',
  cyan_stained_glass: 'cyan_stained_glass',
  purple_stained_glass: 'purple_stained_glass',
  blue_stained_glass: 'blue_stained_glass',
  brown_stained_glass: 'brown_stained_glass',
  green_stained_glass: 'green_stained_glass',
  red_stained_glass: 'red_stained_glass',
  black_stained_glass: 'black_stained_glass',
  brick_block: 'brick_block',
  stone_bricks: 'stone_bricks',
  cracked_stone_bricks: 'cracked_stone_bricks',
  chiseled_stone_bricks: 'chiseled_stone_bricks',
  mossy_stone_bricks: 'mossy_stone_bricks',
  nether_bricks: 'nether_bricks',
  red_nether_bricks: 'red_nether_bricks',
  quartz_block: 'quartz_block',
  chiseled_quartz_block: 'chiseled_quartz_block',
  quartz_pillar: 'quartz_pillar',
  smooth_stone: 'smooth_stone',
  end_stone: 'end_stone',
  end_stone_bricks: 'end_stone_bricks',
  prismarine: 'prismarine',
  prismarine_bricks: 'prismarine_bricks',
  dark_prismarine: 'dark_prismarine',
  sea_lantern: 'sea_lantern',
  crafting_table: 'crafting_table',
  furnace: 'furnace',
  chest: 'chest',
  trapped_chest: 'trapped_chest',
  barrel: 'barrel',
  blast_furnace: 'blast_furnace',
  smoker: 'smoker',
  campfire: 'campfire',
  soul_campfire: 'soul_campfire',
  torch: 'torch',
  soul_torch: 'soul_torch',
  redstone_torch: 'redstone_torch',
  ladder: 'ladder',
  scaffolding: 'scaffolding',
  water: 'water',
  lava: 'lava',
  tnt: 'tnt',
  bedrock: 'bedrock',
  bookshelf: 'bookshelf',
  note_block: 'note_block',
  jukebox: 'jukebox',
  dispenser: 'dispenser',
  dropper: 'dropper',
  piston: 'piston',
  sticky_piston: 'sticky_piston',
  hopper: 'hopper',
  beacon: 'beacon',
  enchantment_table: 'enchantment_table',
  anvil: 'anvil',
  chiseled_bookshelf: 'chiseled_bookshelf',
  iron_block: 'iron_block',
  gold_block: 'gold_block',
  diamond_block: 'diamond_block',
  emerald_block: 'emerald_block',
  redstone_block: 'redstone_block',
  lapis_block: 'lapis_block',
  coal_block: 'coal_block',
  copper_block: 'copper_block',
  copper_ore: 'copper_ore',
  raw_iron: 'raw_iron',
  raw_gold: 'raw_gold',
  raw_copper: 'raw_copper',
  iron_ingot: 'iron_ingot',
  gold_ingot: 'gold_ingot',
  copper_ingot: 'copper_ingot',
  diamond: 'diamond',
  emerald: 'emerald',
  redstone: 'redstone',
  coal: 'coal',
  lapis_lazuli: 'lapis_lazuli',
  quartz: 'quartz',
  flint: 'flint',
  brick: 'brick',
  nether_brick: 'nether_brick',
  netherrack: 'netherrack',
  basalt: 'basalt',
  polished_basalt: 'polished_basalt',
  blackstone: 'blackstone',
  gilded_blackstone: 'gilded_blackstone',
  soul_sand: 'soul_sand',
  soul_soil: 'soul_soil',
  warped_stem: 'warped_stem',
  warped_wart_block: 'warped_wart_block',
  crimson_stem: 'crimson_stem',
  crimson_wart_block: 'crimson_wart_block',
  mushrooms: 'mushroom_stem',
  oak_sapling: 'oak_sapling',
  spruce_sapling: 'spruce_sapling',
  birch_sapling: 'birch_sapling',
  jungle_sapling: 'jungle_sapling',
  acacia_sapling: 'acacia_sapling',
  dark_oak_sapling: 'dark_oak_sapling',
  cherry_sapling: 'cherry_sapling',
  mangrove_propagule: 'mangrove_propagule',
  wheat: 'wheat',
  carrots: 'carrots',
  potatoes: 'potatoes',
  beetroots: 'beetroots',
  pumpkin: 'pumpkin',
  melon: 'melon',
  cactus: 'cactus',
  bamboo: 'bamboo',
  sugar_cane: 'sugar_cane',
  kelp: 'kelp',
  seagrass: 'seagrass',
  tall_grass: 'tall_grass',
  fern: 'fern',
  large_fern: 'large_fern',
};

const ITEM_ALIASES = {
  wood: 'oak_log',
  logs: 'oak_log',
  log: 'oak_log',
  tree: 'oak_log',
  plank: 'oak_planks',
  planks: 'oak_planks',
  stone: 'stone',
  dirt: 'dirt',
  sand: 'sand',
  iron: 'iron_ore',
  coal: 'coal_ore',
  gold: 'gold_ore',
  diamond: 'diamond_ore',
  emerald: 'emerald_ore',
  redstone: 'redstone_ore',
  oak: 'oak_log',
  birch: 'birch_log',
  spruce: 'spruce_log',
  jungle: 'jungle_log',
  acacia: 'acacia_log',
  dark_oak: 'dark_oak_log',
  mangrove: 'mangrove_log',
  cherry: 'cherry_log',
  pale_oak: 'pale_oak_log',
  pickaxe: 'stone_pickaxe',
  sword: 'stone_sword',
  axe: 'stone_axe',
  shovel: 'stone_shovel',
  wooden_pickaxe: 'wooden_pickaxe',
  stone_pickaxe: 'stone_pickaxe',
  iron_pickaxe: 'iron_pickaxe',
  gold_pickaxe: 'golden_pickaxe',
  diamond_pickaxe: 'diamond_pickaxe',
  wooden_axe: 'wooden_axe',
  stone_axe: 'stone_axe',
  iron_axe: 'iron_axe',
  diamond_axe: 'diamond_axe',
  wooden_sword: 'wooden_sword',
  stone_sword: 'stone_sword',
  iron_sword: 'iron_sword',
  diamond_sword: 'diamond_sword',
  wooden_shovel: 'wooden_shovel',
  stone_shovel: 'stone_shovel',
  iron_shovel: 'iron_shovel',
  diamond_shovel: 'diamond_shovel',
};

const WOOD_TYPES = [
  'oak_log', 'birch_log', 'spruce_log', 'jungle_log', 'acacia_log', 'dark_oak_log',
  'mangrove_log', 'cherry_log', 'pale_oak_log',
  'oak_wood', 'birch_wood', 'spruce_wood', 'jungle_wood', 'acacia_wood', 'dark_oak_wood',
  'mangrove_wood', 'cherry_wood', 'pale_oak_wood',
  'oak_planks', 'birch_planks', 'spruce_planks', 'jungle_planks', 'acacia_planks', 'dark_oak_planks',
  'mangrove_planks', 'cherry_planks', 'pale_oak_planks',
  'oak_leaves', 'birch_leaves', 'spruce_leaves', 'jungle_leaves', 'acacia_leaves', 'dark_oak_leaves',
  'mangrove_leaves', 'cherry_leaves', 'azalea_leaves', 'flowering_azalea_leaves'
];

function normalizeBlockInput(value) {
  if (value == null) return '';
  return String(value)
    .trim()
    .toLowerCase()
    .replace(/^minecraft:/i, '')
    .replace(/[\s_-]+/g, '_')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function resolveMinecraftName(value, fallbackMap = {}) {
  const normalized = normalizeBlockInput(value);
  if (!normalized) return '';

  const alias = fallbackMap[normalized] || ITEM_ALIASES[normalized] || BLOCKS[normalized] || normalized;
  return alias;
}

module.exports = {
  BLOCKS,
  WOOD_TYPES,
  ITEM_ALIASES,
  normalizeBlockInput,
  resolveMinecraftName,
};
